name: Update MUI Icons and Publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Checkout only MUI icons folder
        uses: actions/checkout@v3
        with:
          repository: mui/material-ui
          token: ${{ secrets.GITHUB_TOKEN }}
          path: mui-material-ui
          fetch-depth: 1
          sparse-checkout: |
            packages/mui-icons-material/material-icons

      - name: Show 10k_24px.svg contents
        run: |
          echo "===== Contents of 10k_24px.svg ====="
          cat mui-material-ui/packages/mui-icons-material/material-icons/10k_24px.svg
